### ISSUE TITLE
[Question] Is ARM64 a supported architecture?

### ISSUE THREAD

**Issue by julien-faye** [jharno/cubep3m#11]
Hello,

I’d like to ask whether cubep3m is supported on Linux/Mac ARM64 systems ?
Any concerns ?
Any positive/negative experience ?

Thank you!

**Comment by jharno** [comment]
Hi, cubep3m has been successfully installed on all machines we've tried, with various architectures including IBM BlueGene and Linux machines with all of the Intel processors we could find. The Makefile needs to be modified in each case to update the compilation flags, but the code itself usually needs no modifications.

**Comment by jharno** [comment]
There are a number of Makefiles in that directory, hopefully you can get some inspiration by looking at some of these?

**Comment by martin-g** [comment]
This issue could be closed now!
PR #13 added a Github Actions based [CI](https://github.com/jharno/cubep3m/blob/98dc362f7bc5a797b56b730d8d5ddf73938f915e/.github/workflows/ci_linux.yaml#L44) that builds on Linux ARM64 via QEMU - https://github.com/jharno/cubep3m/actions/runs/3411354435/jobs/5675445778
